### ISSUE TITLE
Launching on 1.21.3 results in a crash

### ISSUE THREAD

**Issue by itisphxjupiter** [hamarb123/MCMacOSInputFixes#32]
(yes, i know that 1.21.3 is not technically supported yet)

Here is the crash report:
```java
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-11-30 12:32:02
Description: Bootstrap

java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1661 failed
	at knot//net.minecraft.class_3917.<clinit>(class_3917.java:16)
	at knot//net.minecraft.class_7923.method_47461(class_7923.java:158)
	at knot//net.minecraft.class_7923.method_47485(class_7923.java:246)
	at knot//net.minecraft.class_7923.method_47482(class_7923.java:261)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:986)
	at knot//net.minecraft.class_7923.method_47487(class_7923.java:259)
	at knot//net.minecraft.class_2966.redirect$bkc000$fabric-registry-sync-v0$initialize(class_2966.java:561)
	at knot//net.minecraft.class_2966.method_12851(class_2966.java:66)
	at knot//net.minecraft.client.main.Main.main(Main.java:138)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1661 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 15 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 19 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [macos_input_fixes.mixins.json:PlayerInventoryMixin from mod macos_input_fixes] from phase [DEFAULT] in config [macos_input_fixes.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 22 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyVariable annotation on fixHotbarScrollDirection could not find any targets matching 'Lnet/minecraft/class_1661;method_7373(D)V' in net/minecraft/class_1661. Using refmap macos-input-fixes-refmap.json [INJECT_PREPARE Applicator Phase -> macos_input_fixes.mixins.json:PlayerInventoryMixin from mod macos_input_fixes -> Prepare Injections -> localvar$ccl000$macos_input_fixes$fixHotbarScrollDirection(D)D -> Parse ->  -> Validate Targets]
	at org.spongepowered.asm.mixin.injection.selectors.TargetSelectors.validate(TargetSelectors.java:346)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:369)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:340)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:331)
	at org.spongepowered.asm.mixin.injection.struct.ModifyVariableInjectionInfo.<init>(ModifyVariableInjectionInfo.java:47)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:196)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:664)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1399)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:731)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:315)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 22 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at knot//net.minecraft.class_3917.<clinit>(class_3917.java:16)
	at knot//net.minecraft.class_7923.method_47461(class_7923.java:158)
	at knot//net.minecraft.class_7923.method_47485(class_7923.java:246)
	at knot//net.minecraft.class_7923.method_47482(class_7923.java:261)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:986)
	at knot//net.minecraft.class_7923.method_47487(class_7923.java:259)
	at knot//net.minecraft.class_2966.redirect$bkc000$fabric-registry-sync-v0$initialize(class_2966.java:561)
	at knot//net.minecraft.class_2966.method_12851(class_2966.java:66)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at knot//net.minecraft.client.main.Main.main(Main.java:138)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 1.21.3
	Minecraft Version ID: 1.21.3
	Operating System: Mac OS X (x86_64) version 15.1.1
	Java Version: 21.0.3, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 142828768 bytes (136 MiB) / 587202560 bytes (560 MiB) up to 9999220736 bytes (9536 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel UHD Graphics 630
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MiB): 1536.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: Revision ID: 0x0000, Adapter Firmware Version: 7.55, Adapter Firmware Version: 2.19
	Memory slot #0 capacity (MiB): 32768.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 32768.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 65536.00
	Virtual memory used (MiB): 15162.22
	Swap memory total (MiB): 0.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 736858.25, total: 1660347.00
	Space in storage for workdir (MiB): available: 736858.25, total: 1660347.00
	JVM Flags: 2 total; -Xms512m -Xmx9536m
	Fabric Mods: 
		accessible-step: Accessible Step 1.3.4
		armorposer: Armor Poser 7.0.0
		axiom: Axiom 4.3.2
			com_moulberry_axiomclientapi: axiomclientapi 1.0.0
			com_moulberry_mixinconstraints: mixinconstraints 1.0.1
		better-selection: Better Text Selection 1.6.3
		bridgingmod: Bridging Mod 2.5.1+1.21.3
		carpet: Carpet Mod 1.4.158+v241022
		carpet-extra: Carpet Extra 1.4.158
		cloth-config: Cloth Config v16 16.0.141
			cloth-basic-math: cloth-basic-math 0.6.1
		ctrl-q: Ctrl Q 1.9
		dark-loading-screen: Dark Loading Screen 1.6.15
		entityculling: EntityCulling 1.7.1
		fabric-api: Fabric API 0.109.0+1.21.3
			fabric-api-base: Fabric API Base 0.4.50+119c825640
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.81+fd37071f40
			fabric-biome-api-v1: Fabric Biome API (v1) 14.0.6+fd37071f40
			fabric-block-api-v1: Fabric Block API (v1) 1.0.28+fd37071f40
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.16+fd37071f40
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.4+fd37071f40
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.24+fd37071f40
			fabric-command-api-v1: Fabric Command API (v1) 1.2.58+f71b366f40
			fabric-command-api-v2: Fabric Command API (v2) 2.2.37+c9d82ab240
			fabric-commands-v0: Fabric Commands (v0) 0.2.75+df3654b340
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.8+fd37071f40
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.3+7f945d5b40
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.3+84ebbb0e40
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.3+fd37071f40
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.0+dbad41f140
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 21.0.17+fd37071f40
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.7+fd37071f40
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.8+825023f840
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 2.0.12+c2c3ac4740
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.59+fd37071f40
			fabric-item-api-v1: Fabric Item API (v1) 11.1.7+fd37071f40
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.17+fd37071f40
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.53+fd37071f40
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.51+df3654b340
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.1+6da5ef6940
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.26+3f89f5a540
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.14+fd37071f40
			fabric-message-api-v1: Fabric Message API (v1) 6.0.21+fd37071f40
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 3.0.9+fd37071f40
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.5+fd37071f40
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 17.0.9+fd37071f40
			fabric-particles-v1: Fabric Particles (v1) 4.0.10+fd37071f40
			fabric-recipe-api-v1: Fabric Recipe API (v1) 7.0.4+fd37071f40
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.2+fd37071f40
			fabric-renderer-api-v1: Fabric Renderer API (v1) 4.0.5+fd37071f40
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.9.5+fd37071f40
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.54+73761d2e40
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.15+fd37071f40
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.83+df3654b340
			fabric-rendering-v1: Fabric Rendering (v1) 8.0.7+fd37071f40
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.8+fd37071f40
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.6+fd37071f40
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.34+fd37071f40
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.100+fd37071f40
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.29+fd37071f40
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.3+fd37071f40
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.8+fd37071f40
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		ferritecore: FerriteCore 7.1.0-hotfix
		immediatelyfast: ImmediatelyFast 1.3.2+1.21.3
		itemscroller: Item Scroller 0.25.0-sakura.6
		java: OpenJDK 64-Bit Server VM 21
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		litematica: Litematica 0.20.0-sakura.3
		macos_input_fixes: MacOS Input Fixes 1.7
		malilib: MaLiLib 0.22.0-sakura.7
		minecraft: Minecraft 1.21.3
		minihud: MiniHUD 0.33.0-sakura.8
		modmenu: Mod Menu 12.0.0-beta.1
		mods-command: Mods Command 1.1.8
			adventure-platform-fabric: adventure-platform-fabric 6.1.0
				net_kyori_adventure-api: adventure-api 4.17.0
				net_kyori_adventure-key: adventure-key 4.17.0
				net_kyori_adventure-platform-api: adventure-platform-api 4.3.4
				net_kyori_adventure-platform-mod-shared-fabric-repack: adventure-platform-mod-shared-fabric-repack 6.1.0
				net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.17.0
				net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.17.0
				net_kyori_adventure-text-serializer-ansi: adventure-text-serializer-ansi 4.17.0
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.17.0
				net_kyori_adventure-text-serializer-json: adventure-text-serializer-json 4.17.0
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.17.0
				net_kyori_ansi: ansi 1.1.0
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
				net_kyori_option: option 1.0.0
			cloud: Cloud 2.0.0-beta.9
				fabric-permissions-api-v0: fabric-permissions-api 0.3.1
				io_leangen_geantyref_geantyref: geantyref 1.3.15
				org_incendo_cloud-brigadier: cloud-brigadier 2.0.0-beta.9
				org_incendo_cloud-core: cloud-core 2.0.0
				org_incendo_cloud-minecraft-modded-common-fabric-repack_: cloud-minecraft-modded-common-fabric-repack 2.0.0-beta.9
				org_incendo_cloud-services: cloud-services 2.0.0
			org_incendo_cloud-minecraft-extras: cloud-minecraft-extras 2.0.0-beta.10
			org_spongepowered_configurate-core: configurate-core 4.2.0-SNAPSHOT
			org_spongepowered_configurate-hocon: configurate-hocon 4.2.0-SNAPSHOT
			org_spongepowered_configurate-yaml: configurate-yaml 4.2.0-SNAPSHOT
		moreculling: More Culling 1.1.0
			conditional-mixin: conditional mixin 0.6.3
			mixinsquared: MixinSquared 0.2.0
		nochatreports: No Chat Reports 1.21.3-v2.10.1
		notenoughanimations: NotEnoughAnimations 1.8.1
		placeholder-api: Placeholder API 2.5.1+1.21.3
		raised: Raised 4.0.1
		reeses-sodium-options: Reese's Sodium Options 1.8.0+mc1.21.3
		shiftscrollfix: Shift-Scroll Fix 1.0.1
		sodium: Sodium 0.6.0+mc1.21.3
		sodium-extra: Sodium Extra 0.6.0+mc1.21.3
		tweakeroo: Tweakeroo 0.22.0-sakura.6
		vanillarpc: Vanilla RPC 1.2
			club_minnced_discord-rpc-release: discord-rpc-release v3.4.0
			club_minnced_java-discord-rpc: java-discord-rpc 2.0.2
		viafabricplus: ViaFabricPlus 3.5.2
			com_github_oryxel_cubeconverter: CubeConverter 5ae1e90e4f
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			com_vdurmont_semver4j: semver4j 3.1.0
			com_viaversion_viabackwards-common: viabackwards-common 5.1.2-20241118.134019-9
			com_viaversion_viaversion-common: viaversion-common 5.1.2-20241118.140618-18
			de_florianmichael_classic4j: Classic4J 2.1.1-SNAPSHOT
			io_jsonwebtoken_jjwt-api: jjwt-api 0.12.6
			io_jsonwebtoken_jjwt-gson: jjwt-gson 0.12.6
			io_jsonwebtoken_jjwt-impl: jjwt-impl 0.12.6
			io_netty_netty-codec-http: netty-codec-http 4.1.115
			net_jodah_expiringmap: expiringmap 0.5.10
			net_lenni0451_commons_httpclient: httpclient 1.6.0
			net_lenni0451_mcping: MCPing 1.4.2
			net_lenni0451_mcstructs-bedrock_forms: forms 1.2.1
			net_lenni0451_mcstructs-bedrock_text: text 1.2.1
			net_lenni0451_reflect: Reflect 1.4.0
			net_raphimc_minecraftauth: MinecraftAuth 4.1.1
			net_raphimc_viaaprilfools-common: viaaprilfools-common 3.0.5-20241113.235618-5
			net_raphimc_viabedrock: ViaBedrock 0.0.13-20241117.111706-10
			net_raphimc_vialegacy: ViaLegacy 3.0.6-20241113.235820-5
			net_raphimc_vialoader: ViaLoader 3.0.5-20241113.235950-3
			org_cloudburstmc_netty_netty-transport-raknet: netty-transport-raknet 1.0.0.CR3-SNAPSHOT
			org_lz4_lz4-pure-java: lz4-pure-java 1.8.0
		visuality: Visuality 0.7.8+1.21.3
		vmp: Very Many Players 0.2.0+beta.7.180+1.21.3
			com_ibm_async_asyncutil: asyncutil 0.1.0
		voicechat: Simple Voice Chat 1.21.3-2.5.26
		voxelmap: Voxelmap 1.21.3-1.14.2
		worldedit: WorldEdit 7.3.9+6959-7adf70b
		xaerominimap: Xaero's Minimap 24.6.2
		xaeroworldmap: Xaero's World Map 1.39.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.1+1.21.2-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Launched Version: 1.21.3
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GFLW Platform: <error>
	GL Caps: ERR
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: <unknown>
```

**Comment by hamarb123** [comment]
Should be fixed in 1.8
